version: '3.9'

services:
  
  follows_db:
    image: postgres:latest
    environment:
      POSTGRES_DATABASE: follows_db
      POSTGRES_USER: rioverrain
      POSTGRES_PASSWORD: se/db_password
    secrets:
       - db_password      
    ports:
      - "54320:5432"
    volumes:
      - .postgres_follows_service_data/postgres_data:/var/lib/postgresql/data    
  follows_services:
    image: rioverrain/follows_services:latest
    ports:
      - "7781:7781"
    depends_on:
      - follows_db 
      
  users_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: rioverrain
      POSTGRES_PASSWORD: se/db_password
    secrets:
       - db_password
    ports:
      - "5432:5432"
    volumes:
      - .postgres_users_service_data/postgres_data:/var/lib/postgresql/data
  users_services :
    image: rioverrain/users_services:latest
    ports:
      - "7777:7777"
    depends_on:
      - users_db


  zookeeper:
    image: 'bitnami/zookeeper:3.7.0'
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes


  kafka:
    image: 'bitnami/kafka:2.8.0'
    container_name: kafka
    ports:
      - "9093:9093"
    expose:
      - "9093"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CREATE_TOPICS="kafka_capstone_event_bus:1:1"
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://host.docker.internal:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - ALLOW_PLAINTEXT_LISTENER=yes
           
    depends_on:
      - zookeeper
 

secrets:
   db_password:
     file: se/db_password.txt         



---   

  cassandra_posts:
    image: cassandra:latest
    hostname: cassandra_posts
    ports:
      - "9043:9043"
    volumes:
      - .cassandra_posts_services_data/data:/var/lib/cassandra
    environment:
      - USERNAME=rioverrain
      - PASSWORD=se/db_password
    secrets:
       - db_password  
  posts_services:
    image: rioverrain/posts_services:latest
    ports:
      - "7779:7779"
    depends_on:
      - cassandra_posts
  follows_db:
    image: postgres:latest
    environment:
      POSTGRES_DATABASE: follows_db
      POSTGRES_USER: rioverrain
      POSTGRES_PASSWORD: se/db_password
    secrets:
       - db_password      
    ports:
      - "54320:5432"
    volumes:
      - .postgres_follows_service_data/postgres_data:/var/lib/postgresql/data    
  follows_services:
    image: rioverrain/follows_services:latest
    ports:
      - "7781:7781"
    depends_on:
      - follows_db 

  likes_db:
    image: postgres:latest
    environment:
      POSTGRES_DATABASE: likes_db
      POSTGRES_USER: rioverrain
      POSTGRES_PASSWORD: se/db_password
    secrets:
       - db_password 
    ports:
      - "54321:5432"
    volumes:
      - .postgres_likes_service_data/postgres_data:/var/lib/postgresql/data
  likes_services:
    image: rioverrain/likes_services:latest
    ports:
      - "7782:7782"
    depends_on:
      - likes_db

  users_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: rioverrain
      POSTGRES_PASSWORD: se/db_password
    secrets:
       - db_password  
    ports:
      - "5432:5432"
    volumes:
      - .postgres_users_service_data/postgres_data:/var/lib/postgresql/data
  users_services :
    image: rioverrain/users_services:latest
    ports:
      - "7777:7777"
    depends_on:
      - users_db  

  cassandra_posts:
    image: cassandra:latest
    hostname: cassandra_posts
    ports:
      - "9043:9043"
    volumes:
      - .cassandra_posts_services_data/data:/var/lib/cassandra
    environment:
      - USERNAME: rioverrain
      - PASSWORD: se/db_password
    secrets:
       - db_password  
  posts_services:
    image: rioverrain/posts_services:latest
    ports:
      - "7779:7779"
    depends_on:
      - cassandra_posts    

  cassandra:
    image: cassandra:latest
    hostname: cassandra
    ports:
      - "9042:9042"
    volumes:
      - .cassandra_comments_services_data/data:/var/lib/cassandra
    environment:
      - USERNAME: rioverrain
      - PASSWORD: se/db_password
    secrets:
       - db_password   
  comments_services:
    image: rioverrain/comments_services:latest
    ports:
      - "7778:7778"
    depends_on:
      - cassandra    
secrets:
   db_password:
     file: db_password.txt      
########################################################################################
---
  cassandra_follows:
    image: cassandra:latest
    hostname: cassandra_likes
    ports:
      - "9045:9045"
    volumes:
      - .cassandra_follows_services_data/data:/var/lib/cassandra
    environment:
      - USERNAME: rioverrain
      - PASSWORD: se/db_password
    secrets:
       - db_password  
  follows_services:
    image: rioverrain/follows_services:latest
    ports:
      - "7781:7781"
    depends_on:
      - cassandra_follows 


      
########################################################################################

  cassandra:
    image: cassandra:latest
    hostname: cassandra
    ports:
      - "9042:9042"
    volumes:
      - .cassandra_comments_services_data/data:/var/lib/cassandra
    environment:
      - USERNAME: rioverrain
      - PASSWORD: se/db_password
    secrets:
       - db_password  
  comments_services:
    image: rioverrain/comments_services:latest
    ports:
      - "7778:7778"
    depends_on:
      - cassandra

########################################################################################  

  cassandra_posts:
    image: cassandra:latest
    hostname: cassandra_posts
    ports:
      - "9043:9043"
    volumes:
      - .cassandra_posts_services_data/data:/var/lib/cassandra
    environment:
      - USERNAME: rioverrain
      - PASSWORD: se/db_password
    secrets:
       - db_password  
  posts_services:
    image: rioverrain/posts_services:latest
    ports:
      - "7779:7779"
    depends_on:
      - cassandra_posts

########################################################################################

  cassandra_likes:
    image: cassandra:latest
    hostname: cassandra_likes
    ports:
      - "9044:9044"
    volumes:
      - .cassandra_likes_services_data/data:/var/lib/cassandra
    environment:
      - USERNAME: rioverrain
      - PASSWORD: se/db_password
    secrets:
       - db_password  
  likes_services:
    image: rioverrain/likes_services:latest
    ports:
      - "7782:7782"
    depends_on:
      - cassandra_likes

########################################################################################

  cassandra_follows:
    image: cassandra:latest
    hostname: cassandra_likes
    ports:
      - "9045:9045"
    volumes:
      - .cassandra_follows_services_data/data:/var/lib/cassandra
    environment:
      - USERNAME: rioverrain
      - PASSWORD: se/db_password
    secrets:
       - db_password  
  follows_services:
    image: rioverrain/follows_services:latest
    ports:
      - "7781:7781"
    depends_on:
      - cassandra_follows    

########################################################################################
  
  feeds_services:
    image: rioverrain/feeds_services:latest
    ports:
      - "7780:7780"    
 

     


secrets:
   db_password:
     file: db_password.txt


    # volumes:
    #   - ./postgres-data:/var/lib/postgresql/data

# seed_provider:
#   - class_name: org.apache.cassandra.locator.SimpleSeedProvider
#     parameters:
#          - seeds:  "10.168.66.41,10.176.170.59"
# listen_address:
# endpoint_snitch: GossipingPropertyFileSnitch
  

#   version: "3.7"

# services:
#   cassandra:
#     image: cassandra:latest
#     environment:
#       - CASSANDRA_SEEDS=10.168.66.41,10.176.170.59
#       - CASSANDRA_LISTEN_ADDRESS=192.168.1.100
#       - CASSANDRA_ENDPOINT_SNITCH=RackAwareSnitch
#     ports:
#       - "9042:9042"